### ISSUE TITLE
Authentication Issues...

### ISSUE THREAD

**Issue by seakintruth** [seakintruth/r-podcastindex-org-example#1]
Can't authenticate with httr::GET or POST

R's Digest::sha1 algo isn't producing the same hash as other [examples](https://github.com/Podcastindex-org-Examples)

https://github.com/seakintruth/r-podcastindex-org-example/blob/d3b1cf43a4f1179bd25b640d54d36ce87eb03908/podcasting-index.R#L67

**Comment by seakintruth** [comment]
When I print out the authorization hash for identical key  + secret + epoch(timestamp) I get this hash for python:
```
735659ff7ea083cdc3a73454ac9775a077765545
```
and in R I'm getting this:
```
digest::sha1("...",algo="sha1")
[1] "b317f693116101369bc436212b49a9c01f65b81a"
```

**Comment by stevencrader** [comment]
Is the timestamp correct? Do you get a different value for GMT vs UTC?

**Comment by seakintruth** [comment]
seconds ago:
```
epoch_time <- as.numeric(as.POSIXlt(Sys.time(), "GMT"))
> epoch_time
[1] 1618265016
```
which matches the values for UTC at  https://www.epochconverter.com/

**Comment by seakintruth** [comment]
Figured it out through trial and error: setting serialize = FALSE now results in the same hash!
```
digest("...",algo="sha1",serialize=FALSE)
```

**Comment by seakintruth** [comment]
Tested, works!
